- hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Set up the Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
      update_cache: yes
  - name: Update packages cache
    apt:
      update_cache: yes
  - name: Install packages
    apt:
      name: [
        'apt-transport-https', 
        'ca-certificates', 
        'curl', 
        'software-properties-common', 
        'htop', 
        'neovim', 
        'docker-ce',
        'build-essential',
        'wget', 
        'unzip', 
        'libmariadb-dev', 
        'libjpeg-dev',
        'rsync', 
        'screen', 
        'libssl-dev', 
        'zlib1g-dev', 
        'libbz2-dev',
        'libreadline-dev', 
        'libsqlite3-dev',
        'llvm', 
        'libncurses5-dev',
        'libncursesw5-dev',
        'xz-utils', 
        'tk-dev',
        'libffi-dev',
        'liblzma-dev',
        'python-openssl',
        'git',
        'libxml2-dev',
        'libxslt-dev',
        'mariadb-client-core-10.3',
        'sqlite3',
      ]
      state: present
      update_cache: yes
  - name: Add "jonathan" user to "docker" group
    user:
      name: "jonathan"
      groups: "docker"
      append: yes
  - name: Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
  - name: Remove snapd from Ubuntu
    apt:
      name: snapd
      state: absent
      purge: yes
  - name: Remove snapd-related directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /snap
      - /var/snap
      - /var/lib/snapd
  roles:
    - robertdebock.fail2ban